[project]
name = "spendendings"
version = "1.0.1"
description = "Crowdfunding tracking tool without actual payment."
dependencies = [
    "flask",
    "tabulate",
    "waitress",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"